language: objective-c
install:
- cd Example
script: xctool -workspace S3ZencoderVideoManagerExample.xcworkspace -scheme S3ZencoderVideoManagerExample -configuration Release -sdk iphonesimulator7.0 build
